LibraryManagement/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('myapp/', include('myapp.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='myapp/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]
urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

urlpatterns += [
    path('genre/create/', views.GenreCreate.as_view(), name='genre-create'),
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('genre/<int:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
    path('genre/<int:pk>/update/', views.GenreUpdate.as_view(), name='genre-update'),
    path('genre/<int:pk>/delete/', views.GenreDelete.as_view(), name='genre-delete'),
]

urlpatterns += [
    path('bookinstances/', views.BookInstanceListView.as_view(), name='book-instances'),
    path('bookinstance/<uuid:pk>', views.BookInstanceDetailView.as_view(), name='book-instance-detail'),
    path('bookinstance/create/', views.BookInstanceCreate.as_view(), name='book-instance-create'),
    path('bookinstance/<uuid:pk>/update/', views.BookInstanceUpdate.as_view(), name='book-instance-update'),
    path('bookinstance/<uuid:pk>/delete/', views.BookInstanceDelete.as_view(), name='book-instance-delete'),
]

myapp/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50, help_text='Enter book genre')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,help_text='Enter ISBN number')
    genre = models.ManyToManyField(Genre, help_text='Select genre')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this book')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(max_length=1,choices=LOAN_STATUS,blank=True,default='m',help_text='Book availability')

    def get_absolute_url(self):
        return reverse('book-instance-detail', args=[str(self.id)])

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

myapp/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

myapp/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from myapp.forms import RenewBookForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book, Author, BookInstance, Genre
# Create your views here.

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 5

class BookDetailView(generic.DetailView):
    model = Book

class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre']
    permission_required = 'myapp.can_mark_returned'

class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre']
    permission_required = 'myapp.can_mark_returned'

class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'myapp.can_mark_returned'

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 5

class AuthorDetailView(generic.DetailView):
    model = Author

class AuthorCreate(PermissionRequiredMixin,CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'myapp.can_mark_returned'

class AuthorUpdate(PermissionRequiredMixin,UpdateView):
    model = Author
    fields = '__all__' # Not recommended (potential security issue if more fields added)
    permission_required = 'myapp.can_mark_returned'

class AuthorDelete(PermissionRequiredMixin,DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'myapp.can_mark_returned'

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name ='myapp/bookinstance_list_borrowed_user.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'myapp.can_mark_returned'
    template_name = 'myapp/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

@login_required
@permission_required('myapp.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return HttpResponseRedirect(reverse('all-borrowed') )
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
    context = {
        'form': form,
        'book_instance': book_instance,
    }
    return render(request, 'myapp/book_renew_librarian.html', context)

class BookInstanceCreate(PermissionRequiredMixin,CreateView):
    model = BookInstance
    fields = ['book','imprint','due_back','borrower','status']
    permission_required = 'myapp.can_mark_returned'
    def get_success_url(self):
        return reverse('book-detail', kwargs={'pk': self.object.book.pk})

class BookInstanceUpdate(PermissionRequiredMixin,UpdateView):
    model = BookInstance
    fields = ['book','imprint','due_back','borrower','status']
    permission_required = 'myapp.can_mark_returned'
    def get_success_url(self):
        return reverse('book-instance-detail', kwargs={'pk': self.object.pk})

class BookInstanceDelete(PermissionRequiredMixin, DeleteView):
    model = BookInstance
    success_url = reverse_lazy('book-instances')
    permission_required = 'myapp.can_mark_returned'
    # def get_success_url(self):
    #     return reverse('book-detail', kwargs={'pk': self.object.book.pk})

class BookInstanceListView(generic.ListView):
    model = BookInstance
    template_name = 'myapp/bookinstance_list.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.all()

class BookInstanceDetailView(generic.DetailView):
    model = BookInstance

class GenreDelete(PermissionRequiredMixin, DeleteView):
    model = Genre
    success_url = reverse_lazy('genres')
    permission_required = 'myapp.can_mark_returned'

class GenreCreate(PermissionRequiredMixin,CreateView):
    model = Genre
    fields = ['name']
    permission_required = 'myapp.can_mark_returned'

class GenreListView(generic.ListView):
    model = Genre
    paginate_by = 5

class GenreDetailView(generic.DetailView):
    model = Genre

class GenreUpdate(PermissionRequiredMixin,UpdateView):
    model = Genre
    fields = '__all__' # Not recommended (potential security issue if more fields added)
    permission_required = 'myapp.can_mark_returned'

class GenreDelete(PermissionRequiredMixin, DeleteView):
    model = Genre
    success_url = reverse_lazy('genres')
    permission_required = 'myapp.can_mark_returned'

myapp/templates/myapp/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

myapp/templates/myapp/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

myapp/templates/myapp/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

myapp/templates/myapp/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Genre:</strong> 
    {% for genre in book.genre.all %}
    <a href="{% url 'genre-detail' genre.pk %}">{{genre}},</a>
    {% endfor %}
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>
      {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
          {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
          <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
      {% endfor %}
  </div>
  {% if perms.myapp.can_mark_returned %}
  <a href="{% url 'book-update' book.pk %}" class="text-warning">Update Book</a>  <a href="{% url 'book-delete' book.pk %}" class="text-danger">Delete Book</a>
  {% endif %}
{% endblock %}

myapp/templates/myapp/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

myapp/templates/myapp/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

myapp/templates/myapp/bookinstance_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book Instance</h1>

<p>Are you sure you want to delete this book instance: {{ bookinstance }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

myapp/templates/myapp/bookinstance_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ bookinstance.book.title }}</h1>
  <div style="margin-left:20px;margin-top:20px">
        <p class="{% if bookinstance.status == 'a' %}text-success{% elif bookinstance.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
          {{ bookinstance.get_status_display }}
        </p>
        {% if bookinstance.status != 'a' %}
          <p><strong>Due to be returned:</strong> {{ bookinstance.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{ bookinstance.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong> {{ bookinstance.id }}</p>
  </div>
  {% if perms.myapp.can_mark_returned %}
  <a href="{% url 'book-instance-update' bookinstance.pk %}" class="text-warning">Update Book Instance</a>  <a href="{% url 'book-instance-delete' bookinstance.pk %}" class="text-danger">Delete Book instance</a>
  {% endif %}
{% endblock %}

myapp/templates/myapp/bookinstance_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

myapp/templates/myapp/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ,Book Due on- ({{ bookinst.due_back }}) {% if user.is_staff %} ,Book borrowed by- {{ bookinst.borrower }}{% endif %} {% if perms.myapp.can_mark_returned %} <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

myapp/templates/myapp/genre_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Genre</h1>

<p>Are you sure you want to delete this genre: {{ genre }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

myapp/templates/myapp/genre_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Genre: {{ genre }} </h1>
{% if perms.myapp.can_mark_returned %}
<a href="{% url 'genre-update' genre.pk %}" class="text-warning">Update Genre</a>  <a href="{% url 'genre-delete' genre.pk %}" class="text-danger">Delete Genre</a>
{% endif %}
<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

<dl>
{% for book in genre.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> {{book.bookinstance_set.all.count}} copies available</dt>
  <dd>{{book.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

myapp/templates/myapp/genre_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

myapp/templates/myapp/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Genre List</h1>
  {% if genre_list %}
  <ul>
    {% for genre in genre_list %}
      <li>
        <a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no genres in the library.</p>
  {% endif %} 
{% endblock %}